language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2
    - os: windows

git:
  depth: 1
  submodules: false

before_install:
  - export -f travis_nanoseconds travis_time_start travis_time_finish
  - if ! [ -x ./test ]; then git submodule update --init --recursive $([ $TRAVIS_OS_NAME = windows ] || echo --depth 1) .cppsm; fi

script:
  - if [ -x ./test ]; then ./test; else .cppsm/.cli/travis-ci; fi
