language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - GNU_CC="gcc-8"
        - GNU_CXX="g++-8"
        - CLANG_CC="clang"
        - CLANG_CXX="clang++"
    - os: osx
      osx_image: xcode10.2
    - os: windows

git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - .cppsm/travis-ci || ./test
