language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2
    - os: windows

git:
  submodules: false

before_install:
  - export -f travis_nanoseconds travis_time_start travis_time_finish
  - git submodule update --init

script:
  - if [ -x ./test ]; then ./test; else .cppsm/travis-ci; fi
