#!/bin/bash -e

if ! command -v curl > /dev/null; then
  >&2 echo "WARNING: Could not find curl ( https://curl.haxx.se/ )."
fi

if ! command -v jq > /dev/null; then
  >&2 echo "WARNING: Could not find jq ( https://stedolan.github.io/jq/ )."
fi

__cppsm_complete() {
  local IFS=$' \t\n'
  COMPREPLY=()
  local PREVIOUS="${3#\"}"
  PREVIOUS="${PREVIOUS%\"}"
  local CURRENT="${2#\"}"
  CURRENT="${CURRENT%\"}"
  case "$PREVIOUS" in
    cppsm)
      # shellcheck disable=SC2207
      COMPREPLY=($(compgen -W "add build build-watch clone format init init-hello init-library list remove setup test test-watch update upgrade" -- "$CURRENT"))
      ;;
    add)
      # shellcheck disable=SC2207
      COMPREPLY=($(compgen -W "equipment requires" -- "$CURRENT"))
      ;;
    clone)
      if command -v jq > /dev/null && command -v curl > /dev/null; then
        # shellcheck disable=SC2207
        COMPREPLY=($(curl -s "https://api.github.com/search/repositories?q=topic:cppsm+${CURRENT##*/}" | \
                       jq '.items | .[] | .ssh_url'))
      fi
      ;;
    equipment|requires)
      if command -v jq > /dev/null && command -v curl > /dev/null; then
        # shellcheck disable=SC2207
        COMPREPLY=($(curl -s "https://api.github.com/search/repositories?q=topic:cppsm+${CURRENT##*/}" | \
                       jq '.items | .[] | .clone_url'))
      fi
      ;;
    https:*.git|git*.git)
      # shellcheck disable=SC2207
      COMPREPLY=($(git ls-remote --heads "$PREVIOUS" | sed -e 's#[^ ]*\s*refs/heads/##g'))
      ;;
    *)
      ;;
  esac
}

complete -F __cppsm_complete -o default cppsm
