#!/bin/bash -e

git init
VERSION=v1 cppsm init-hello

git commit -m Initial

git submodule --quiet add -b v1 https://github.com/per-framework/dumpster.cpp.git equipment/dumpster.cpp/v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1
cppsm add requires https://github.com/per-framework/dumpster.cpp.git v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1

cppsm list

cppsm remove requires/polyfill.cpp/v1

if cppsm list; then
  exit 1
fi
