#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ $# -ne 2 ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD url branch

Clones the specified cppsm compatible repository and its dependencies.
EOF
  exit 1
fi

NAME="${1%.git}"
NAME="${NAME##*/}"

git clone "${GIT_QUIET[@]}" --branch "$2" "$1"
cd "$NAME"
git submodule "${GIT_QUIET[@]}" update --init --jobs "$N_PARALLEL_UPDATE"
