#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ "$#" -ne 0 ] || [ ! -d .git ] ; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Formats project files inplace using
- clang-format ( https://clang.llvm.org/docs/ClangFormat.html ), and
- prettier ( https://prettier.io/ ).
EOF
  exit 1
fi

NO_RUN_IF_EMPTY=()
if [[ "$OSTYPE" != "darwin"* ]]; then NO_RUN_IF_EMPTY+=(--no-run-if-empty); fi

for ROOT in provides internals ; do
  find $ROOT -name '*.md' -print0 | xargs "${NO_RUN_IF_EMPTY[@]}" -0 prettier --write --
  for SUFFIX in cpp hpp ; do
    find $ROOT -name "*.$SUFFIX" -print0 | xargs "${NO_RUN_IF_EMPTY[@]}" -0 clang-format -i --
  done
done

find . -maxdepth 1 -name '*.md' -print0 | xargs "${NO_RUN_IF_EMPTY[@]}" -0 prettier --write --
