#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ "$#" -ne 0 ] || [ ! -d .git ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Initializes a new C++ project with cppsm configuration files or updates an
existing project to use the latest configuration files.  Run $CMD in the
top-level directory of a fresh git project.
EOF
  exit 1
fi

if [ -n "$TRAVIS_BRANCH" ]; then
  CLI_BRANCH="$TRAVIS_BRANCH"
else
  CLI_BRANCH=$(git -C "${BASH_SOURCE%/*}" rev-parse --abbrev-ref HEAD)
fi

BOILERPLATE_URL="https://github.com/cppsm/cppsm-boilerplate.git"

if [ ! -d .cppsm ]; then
  if git ls-remote --heads "$BOILERPLATE_URL" | grep -q "\brefs/heads/$CLI_BRANCH\$"; then
    BOILERPLATE_BRANCH="$CLI_BRANCH"
  else
    BOILERPLATE_BRANCH="master"
  fi
  git submodule "${GIT_QUIET[@]}" add --branch "$BOILERPLATE_BRANCH" "$BOILERPLATE_URL" .cppsm
fi

ln -fs .cppsm/.clang-format .clang-format
ln -fs .cppsm/.gitignore .gitignore
ln -fs .cppsm/.prettierrc .prettierrc

if [ ! -e CMakeLists.txt ]; then
  cat << EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.10)
project(${PWD##*/})
include(.cppsm/c++17.cmake)
EOF
fi

cp "$CPPSM/.travis.yml" .travis.yml

git add \
    .clang-format \
    .gitignore \
    .prettierrc \
    .travis.yml \
    CMakeLists.txt
