#!/bin/bash -e

# shellcheck source=init
. "${BASH_SOURCE%/*}/init"

# Library boilerplate

add-file provides/CMakeLists.txt << EOF
add_conventional_library(${NAME}_${VERSION})
EOF

add-file "provides/include/${NAME}_${VERSION}/synopsis.hpp" << EOF
#pragma once

namespace ${NAME}_${VERSION} {

// TODO

}
EOF

# Testing boilerplate

add-file internals/CMakeLists.txt << EOF
add_conventional_executable_tests(PRIVATE ${NAME}_${VERSION})
EOF

add-file internals/testing/compile_synopsis_test.cpp << EOF
#include "${NAME}_${VERSION}/synopsis.hpp"

int main() { return 0; }
EOF
