#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

to-cpp() {
  echo "$1" \
    | sed -e 's#[^a-zA-Z0-9_]#_#g' \
          -e 's#__*#_#g' \
          -e 's#^_##' \
          -e 's#_$##'
}

if [ -z "$NAME" ]; then
  NAME="${PWD##*/}"
fi
NAME="$(to-cpp "$NAME")"

if [ -z "$VERSION" ]; then
  if git symbolic-ref --short HEAD > /dev/null 2>&1; then
    VERSION="$(git symbolic-ref --short HEAD)"
  fi
fi
if [ -z "$VERSION" ]; then
  VERSION="v1"
fi
VERSION="$(to-cpp "$VERSION")"

if [ $# -ne 0 ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Options:

  NAME=$NAME|...
  VERSION=$VERSION|...

Initializes a new project with cppsm configuration files when run in an empty
directory or updates an existing project to use the latest configuration files.
EOF
  exit 1
fi

if [ ! -e .git ] || [ -z "$NAME" ] || [ -z "$VERSION" ]; then
  git init
fi

if [ "$(git symbolic-ref --short HEAD)" != "$VERSION" ]; then
  git checkout -b "$VERSION"
fi

if [ -n "$TRAVIS_BRANCH" ]; then
  CLI_BRANCH="$TRAVIS_BRANCH"
else
  CLI_BRANCH=$(git -C "${BASH_SOURCE%/*}" rev-parse --abbrev-ref HEAD)
fi

BOILERPLATE_URL="https://github.com/cppsm/cppsm-boilerplate.git"

if [ ! -d .cppsm ]; then
  if git ls-remote --heads "$BOILERPLATE_URL" \
      | grep -q "\brefs/heads/$CLI_BRANCH\$"; then
    BOILERPLATE_BRANCH="$CLI_BRANCH"
  else
    BOILERPLATE_BRANCH="master"
  fi
  git submodule "${GIT_QUIET[@]}" add --branch "$BOILERPLATE_BRANCH" \
      "$BOILERPLATE_URL" .cppsm
fi

create-parent-dir() {
  local FILE="$1"
  if [[ "$FILE" =~ / ]]; then mkdir -p "${FILE%/*}"; fi
}

add-file() {
  local FILE="$1"
  if [ ! -e "$FILE" ]; then
    create-parent-dir "$FILE"
    cat > "$FILE"
    git add "$FILE"
  fi
}

add-file .clang-format << EOF
BinPackArguments: false
BinPackParameters: false
ColumnLimit: 80
IndentWidth: 2
EOF

add-file .gitignore << EOF
.build*
EOF

add-file .prettierrc << EOF
{
  "bracketSpacing": false,
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "proseWrap": "always"
}
EOF

add-file CMakeLists.txt << EOF
cmake_minimum_required(VERSION 3.10)
project($NAME)
include(.cppsm/c++17.cmake)
EOF

add-file .travis.yml < "$CPPSM/.travis.yml"
