#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ "$#" -ne 0 ] || [ ! -f CMakeLists.txt ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: [option=value ...] $CMD

Options:

  CMAKE_BUILD_TYPE=Debug|Release
  CMAKE_GENERATOR=|...

  CTEST_OUTPUT_ON_FAILURE=1|0
  CTEST_VERBOSITY=|quiet|verbose

  CC=cc|gcc|clang|...
  CXX=c++|g++|clang++|...

  CLEAN=0|1

  COVERAGE=0|1

  NUMBER_OF_PROCESSORS=1|2|...
  N_PARALLEL_BUILD=1|2|...
  N_PARALLEL_TEST=1|2|...

Run $CMD in a directory containing CMakeLists.txt.
EOF
  exit 1
fi

# Meta -------------------------------------------------------------------------

if (set +x && [ -z "$CMAKE_HELP" ]); then
  CMAKE_HELP="$(cmake --help)"
fi

cmake-help-contains() {
  (set +x && [[ "$CMAKE_HELP" =~ $1 ]])
}

# Generate ---------------------------------------------------------------------

GENERATE_CMD=(cmake "-Werror=dev" "-Werror=deprecated" "-DCPPSM=1")
BUILD_DIR=".build"

# Compiler

if [ -n "$CXX" ]; then
  BUILD_DIR="$BUILD_DIR.$CXX"
fi

# Generator

if [ -n "$CXX" ] && [ -z "$CMAKE_GENERATOR" ] \
     && cmake-help-contains "MSYS Makefiles"; then
  export CMAKE_GENERATOR="MSYS Makefiles"
fi

if [ "$CMAKE_GENERATOR" = "MSYS Makefiles" ]; then
  export CMAKE_MAKE_PROGRAM="make"
fi

if [ -n "$CMAKE_GENERATOR" ]; then
  BUILD_DIR="$BUILD_DIR.${CMAKE_GENERATOR// /_}"
  GENERATE_CMD+=("-G" "$CMAKE_GENERATOR")
fi

# Build type

CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Debug}"

if [[ "$CMAKE_GENERATOR" =~ Makefiles|Ninja ]] || \
     ([ -z "$CMAKE_GENERATOR" ] && ! cmake-help-contains 'Visual Studio'); then
  BUILD_DIR="$BUILD_DIR.$CMAKE_BUILD_TYPE"
  GENERATE_CMD+=("-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE")
fi

# Coverage

COVERAGE="${COVERAGE:-0}"
if [ "$COVERAGE" = 1 ]; then
  BUILD_DIR="$BUILD_DIR.coverage"
  GENERATE_CMD+=("-DCOVERAGE=ON")
fi

# Finish

GENERATE_CMD+=(..)

# Clean

CLEAN="${CLEAN:-0}"
if [ "$CLEAN" = 1 ]; then
  rm -rf "$BUILD_DIR"
fi

# Generate

mkdir -p "$BUILD_DIR" && cd "$_"
"${GENERATE_CMD[@]}"

# Build and Test ---------------------------------------------------------------

export CTEST_OUTPUT_ON_FAILURE="${CTEST_OUTPUT_ON_FAILURE:-1}"

N_PARALLEL_BUILD="${N_PARALLEL_BUILD:-$NUMBER_OF_PROCESSORS}"
N_PARALLEL_TEST="${N_PARALLEL_TEST:-$NUMBER_OF_PROCESSORS}"

export BUILD_CMD=()
export TEST_CMD=()
if command -v nice > /dev/null; then
  BUILD_CMD+=(nice)
  TEST_CMD+=(nice)
fi
BUILD_CMD+=(cmake --build . --config "$CMAKE_BUILD_TYPE" --parallel "$N_PARALLEL_BUILD" --)
TEST_CMD+=(ctest --build-config "$CMAKE_BUILD_TYPE" --parallel "$N_PARALLEL_TEST")

# Quiet

if [[ "$CMAKE_GENERATOR" =~ 'Visual Studio' ]] || \
     ([ -z "$CMAKE_GENERATOR" ] && cmake-help-contains "Visual Studio"); then
  if [ "$QUIET" != 0 ]; then
    MSBUILD_VERBOSITY="${MSBUILD_VERBOSITY:-QUIET}"
  fi
  if [ -n "$MSBUILD_VERBOSITY" ]; then
    BUILD_CMD+=("/VERBOSITY:$MSBUILD_VERBOSITY")
  fi
fi

if [[ "$CMAKE_GENERATOR" =~ Xcode ]]; then
  if [ "$QUIET" != 0 ]; then
    XCODE_VERBOSITY="${XCODE_VERBOSITY:-quiet}"
  fi
  if [ -n "$XCODE_VERBOSITY" ]; then
    BUILD_CMD+=("-$XCODE_VERBOSITY")
  fi
fi

if [ -n "$CTEST_VERBOSITY" ]; then
  TEST_CMD+=("--$CTEST_VERBOSITY")
fi

# Watch ------------------------------------------------------------------------

export WATCH_CMD=(fswatch --one-per-batch --recursive)

if [[ "$OSTYPE" =~ ^(linux-gnu|msys|cygwin)$ ]]; then
  # The default monitor notifies on read accesses...
  WATCH_CMD+=(--monitor poll_monitor '--latency=5')
fi

WATCH_CMD+=(../*)
