#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ "$#" -ne 0 ] || [ ! -e .gitmodules ] ; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Pulls the current git branch and updates all cppsm managed submodules to the
versions in the branch.
EOF
  exit 1
fi

git pull -r

update-by-key () {
  local KEY="$1"
  local DIR
  DIR="$(git config --file .gitmodules --get "$KEY")"
  git submodule update --init -- "$DIR"
}

for KEY in $(git config \
                 --file .gitmodules \
                 --name-only \
                 --get-regexp "^submodule\.(equipment|requires)/.*\.path$"); do
  update-by-key "$KEY"
done

update-by-key "submodule..cppsm.path"
