#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ $# -ne 0 ] || [ ! -e .gitmodules ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Pulls the current git branch and updates all cppsm managed submodules to the
versions in the branch.
EOF
  exit 1
fi

git pull "${GIT_QUIET[@]}" --rebase

MODULES=(.cppsm)
add-submodule-paths-to MODULES .gitmodules 'equipment|requires'

git submodule "${GIT_QUIET[@]}" update --jobs "$N_PARALLEL_UPDATE" --init -- "${MODULES[@]}"
