#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ "$#" -ne 0 ] || [ ! -e .gitmodules ] ; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Upgrades all cppsm managed submodules to latest remote versions and runs init to
update configuration files.
EOF
  exit 1
fi

upgrade-by-key () {
  local KEY="$1"
  local DIR
  DIR="$(git config --file .gitmodules --get "$KEY")"
  git submodule "${GIT_QUIET[@]}" update --remote -- "$DIR"
  git add "$DIR"
}

for KEY in $(git config \
                 --file .gitmodules \
                 --name-only \
                 --get-regexp "^submodule\.(equipment|requires)/.*\.path$"); do
  upgrade-by-key "$KEY"
done

upgrade-by-key "submodule..cppsm.path"

"$CPPSM/commands/init"
