#!/bin/bash -e

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

if [ $# -ne 0 ] || [ ! -e .gitmodules ]; then
  CMD="${0##*/}"
  cat << EOF
Usage: $CMD

Upgrades all cppsm managed submodules to latest remote versions and runs cppsm
init to update configuration files.
EOF
  exit 1
fi

MODULES=(.cppsm)
while IFS='' read -r line; do
  MODULES+=("$line")
done < <(git config \
             --file .gitmodules \
             --get-regexp "^submodule\.(equipment|requires)/.*\.path$" \
           | sed -e 's#^.*\.path ##g')

git submodule "${GIT_QUIET[@]}" update --jobs "$N_PARALLEL_UPDATE" --remote -- "${MODULES[@]}"
git add "${MODULES[@]}"

"$CPPSM/commands/init"
