#!/bin/bash -e

export PATH="$PWD/bin:$PATH"

# shellcheck source=../commands/.settings
. commands/.settings

# git config

if [ "$TRAVIS" = true ]; then
  git config --global core.autocrlf false
  git config --global user.email "ci@script.com"
  git config --global user.name "CI script"
fi

# Run tests

folded() {
  FOLD=$((FOLD+1))
  echo -e "travis_fold:start:cppsm.$FOLD\033[33;1m$1\033[0m"
  travis_time_start
  shift
  echo "$@"
  "$@"
  travis_time_finish
  echo -e "\ntravis_fold:end:cppsm.$FOLD\r"
}

run-test() {
  mkdir "$NAME"
  pushd "$NAME" > /dev/null
  "../$TEST"
  popd
}

for TEST in .cppsm/testing/* ; do
  NAME="${TEST##*/}"
  folded "$NAME" run-test
done

# Test travis-ci script

mkdir travis_ci_test && cd "$_"

NAME=hello VERSION=v1 cppsm init-hello
git commit -m Initial

../travis-ci
