#!/bin/bash -e

export PATH="$PWD/bin:$PATH"

# shellcheck source=../commands/.settings
. commands/.settings

mkdir self-test && cd "$_"

git init
cppsm init
cppsm hello

git config --global user.email "ci@script.com"
git config --global user.name "CI script"
git commit -m Initial

../travis-ci

git submodule --quiet add -b v1 https://github.com/per-framework/dumpster.cpp.git equipment/dumpster.cpp/v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1
cppsm add requires https://github.com/per-framework/dumpster.cpp.git v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1

cppsm list

cppsm remove requires/polyfill.cpp/v1

if cppsm list; then
  exit 1
fi
