#!/bin/bash -e

export PATH="$PWD/bin:$PATH"

# shellcheck source=../commands/.settings
. commands/.settings

# git config

git config --global core.autocrlf false
git config --global user.email "ci@script.com"
git config --global user.name "CI script"

# init-library

mkdir library && cd "$_"

git init
cppsm init-library
CXX='' CC='' cppsm test

cd ..

# add_subdirectory test

mkdir -p subdir/hello && cd "$_"

git init
cppsm init-hello

cd ..
cat << EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.10)
project(subdir_test)
add_subdirectory(hello)
EOF

mkdir .build && cd "$_"
cmake ..
cmake --build .

if [ -n "$(find . -name "message_test*")" ]; then exit 1; fi

cd ../..

# self test

mkdir hello && cd "$_"

git init
cppsm init-hello

git commit -m Initial

../travis-ci

git submodule --quiet add -b v1 https://github.com/per-framework/dumpster.cpp.git equipment/dumpster.cpp/v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1
cppsm add requires https://github.com/per-framework/dumpster.cpp.git v1
cppsm add equipment https://github.com/per-framework/dumpster.cpp.git v1

cppsm list

cppsm remove requires/polyfill.cpp/v1

if cppsm list; then
  exit 1
fi
